/* ============================================================
   Nail Studio — Full Booking App
   ============================================================
   Настройки:
   - SUPABASE_URL / SUPABASE_ANON_KEY: вставь свои данные
   - EMAILJS_*: вставь свои данные (опционально)

   SQL для Supabase (выполнить в SQL Editor):
     CREATE TABLE bookings (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       name TEXT NOT NULL,
       phone TEXT NOT NULL,
       service TEXT NOT NULL,
       date DATE NOT NULL,
       time TEXT NOT NULL,
       comment TEXT DEFAULT '',
       created_at TIMESTAMPTZ DEFAULT NOW()
     );
     ALTER TABLE bookings ADD CONSTRAINT unique_slot UNIQUE (date, time);
     CREATE POLICY "Allow anonymous insert" ON bookings
       FOR INSERT TO anon WITH CHECK (true);
   ============================================================ */

// ==================== CONFIG ====================
// Вставь свои ключи ниже:

const SUPABASE_URL = 'https://YOUR_PROJECT.supabase.co'
const SUPABASE_ANON_KEY = 'YOUR_ANON_KEY'

const EMAILJS_PUBLIC_KEY = 'YOUR_PUBLIC_KEY'
const EMAILJS_SERVICE_ID = 'YOUR_SERVICE_ID'
const EMAILJS_TEMPLATE_ID = 'YOUR_TEMPLATE_ID'

// ==================== DATA ====================

const SERVICES = [
  { id: 1, title: 'Маникюр с покрытием', desc: 'Классический маникюр + гель-лак', price: 2500, duration: 60, image: 'https://images.unsplash.com/photo-1607779097040-26e80aa78e66?w=400&q=80' },
  { id: 2, title: 'Маникюр без покрытия', desc: 'Классический или аппаратный маникюр', price: 1800, duration: 40, image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&q=80' },
  { id: 3, title: 'Укрепление ногтей', desc: 'Акригель или полигель', price: 1000, duration: 20, image: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?w=400&q=80' },
  { id: 4, title: 'Наращивание', desc: 'Любая длина и форма', price: 3500, duration: 90, image: 'https://images.unsplash.com/photo-1610992015732-2449b5e2b89b?w=400&q=80' },
  { id: 5, title: 'Дизайн ногтей', desc: 'Френч, градиент, слайдеры, стразы', price: 500, duration: 30, image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&q=80' },
  { id: 6, title: 'Педикюр', desc: 'Аппаратный педикюр + покрытие', price: 3000, duration: 60, image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&q=80' },
]

const TIME_SLOTS = ['10:00', '12:00', '14:00', '16:00', '18:00']

// ==================== HELPERS ====================

function fmtPrice(p) { return p.toLocaleString('ru-RU') + ' \u20BD' }
function fmtDate(d) {
  return new Date(d).toLocaleDateString('ru-RU', { weekday: 'short', day: 'numeric', month: 'long' })
}
function fmtISO(d) { return new Date(d).toISOString().split('T')[0] }
function fmtMonth(y, m) { return new Date(y, m, 1).toLocaleDateString('ru-RU', { month: 'long', year: 'numeric' }) }
function getSvc(id) { return SERVICES.find(s => s.id === id) }

// ==================== STATE ====================

const S = {
  step: 0, serviceId: null, date: null, time: null,
  name: '', phone: '', comment: '',
  booked: {}, month: new Date().getMonth(), year: new Date().getFullYear(),
  loading: false,
}

// ==================== DOM REFS ====================

const $id = id => document.getElementById(id)
const $q = sel => document.querySelector(sel)
const $qa = sel => [...document.querySelectorAll(sel)]

// ==================== BOOKING ENGINE ====================

const B = {
  async open(svcId) {
    this.reset()
    if (svcId) S.serviceId = svcId
    S.booked = await fetchBooked()
    const el = $id('bookingOverlay')
    if (!el) return
    el.classList.add('active')
    document.body.style.overflow = 'hidden'
    this.render(0)
    this.ui()
  },

  close() {
    const el = $id('bookingOverlay')
    if (el) el.classList.remove('active')
    document.body.style.overflow = ''
    this.reset()
  },

  reset() {
    S.step = 0; S.serviceId = null; S.date = null; S.time = null
    S.name = ''; S.phone = ''; S.comment = ''
    S.month = new Date().getMonth(); S.year = new Date().getFullYear()
    S.loading = false
  },

  go(n) { S.step = n; this.render(n); this.ui() },
  back() { S.step > 0 ? this.go(S.step - 1) : this.close() },

  render(n) {
    const content = $id('bookingContent')
    if (!content) return
    content.innerHTML = ''
    const el = [this.svcStep, this.dateStep, this.timeStep, this.confStep, this.okStep][n].call(this)
    if (el) { el.classList.add('booking-step'); content.appendChild(el); content.scrollTop = 0 }
  },

  // ---- STEP 0: Services ----
  svcStep() {
    const div = c('div', 'space-y-5 py-2')
    div.appendChild(c('h2', 'text-2xl font-bold tracking-tight', 'Выберите услугу'))
    const grid = c('div', 'space-y-3')

    SERVICES.forEach(s => {
      const sel = S.serviceId === s.id
      const card = c('div', `service-card flex items-center gap-4 p-4 rounded-2xl border ${sel ? 'selected border-white/40 bg-white/[0.06]' : 'border-white/[0.06] bg-white/[0.02]'}`)
      card.innerHTML = `
        <div class="w-16 h-16 rounded-xl overflow-hidden shrink-0 bg-white/[0.05]">
          <img src="${s.image}" alt="${s.title}" class="w-full h-full object-cover" loading="lazy">
        </div>
        <div class="flex-1 min-w-0">
          <div class="flex items-start justify-between gap-2">
            <h3 class="text-sm font-medium truncate">${s.title}</h3>
            <span class="text-sm font-semibold shrink-0">${fmtPrice(s.price)}</span>
          </div>
          <p class="text-xs text-white/40 mt-0.5">${s.desc}</p>
          <span class="text-[11px] text-white/30">~ ${s.duration} мин</span>
        </div>
        <div class="check w-5 h-5 rounded-full ${sel ? 'bg-white' : 'bg-white/20'} flex items-center justify-center shrink-0 transition-all duration-300">
          <svg class="w-3 h-3 ${sel ? 'text-[#0a0a0a]' : 'text-transparent'}" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"/></svg>
        </div>
      `
      card.onclick = () => { S.serviceId = s.id; this.render(0); this.ui() }
      grid.appendChild(card)
    })
    div.appendChild(grid)
    return div
  },

  // ---- STEP 1: Calendar ----
  dateStep() {
    const { year: y, month: m } = S
    const div = c('div', 'space-y-5 py-2')
    div.appendChild(c('h2', 'text-2xl font-bold tracking-tight', 'Выберите дату'))

    const nav = c('div', 'flex items-center justify-between mb-2')
    nav.innerHTML = `
      <span class="month-nav" id="pm">&#8249;</span>
      <span class="text-sm font-medium">${fmtMonth(y, m)}</span>
      <span class="month-nav" id="nm">&#8250;</span>
    `
    div.appendChild(nav)

    const hdr = c('div', 'grid grid-cols-7 mb-1')
    'Пн Вт Ср Чт Пт Сб Вс'.split(' ').forEach(d => {
      const el = c('div', 'text-center text-[11px] text-white/30 py-2 font-medium', d)
      hdr.appendChild(el)
    })
    div.appendChild(hdr)

    const grid = c('div', 'grid grid-cols-7')
    const first = new Date(y, m, 1)
    const last = new Date(y, m + 1, 0)
    const off = (first.getDay() + 6) % 7

    for (let i = off - 1; i >= 0; i--) grid.appendChild(c('div', 'calendar-day padding'))

    const today = new Date(); today.setHours(0, 0, 0, 0)
    for (let d = 1; d <= last.getDate(); d++) {
      const dt = new Date(y, m, d)
      const ds = fmtISO(dt)
      const busy = (S.booked[ds] || []).length >= TIME_SLOTS.length
      const past = dt < today
      const dis = past || busy
      const el = c('div', `calendar-day ${dis ? 'disabled' : ''} ${!dis && dt.getTime() === today.getTime() ? 'today' : ''} ${S.date === ds ? 'selected' : ''}`, '' + d)
      if (!dis) el.onclick = () => { S.date = ds; this.render(1); this.ui() }
      grid.appendChild(el)
    }
    div.appendChild(grid)

    // Month nav
    requestAnimationFrame(() => {
      const p = $id('pm'), n = $id('nm')
      if (p) p.onclick = async () => {
        if (S.month === 0) { S.month = 11; S.year-- } else S.month--
        S.booked = await fetchBooked(); this.render(1); this.ui()
      }
      if (n) n.onclick = async () => {
        if (S.month === 11) { S.month = 0; S.year++ } else S.month++
        S.booked = await fetchBooked(); this.render(1); this.ui()
      }
    })

    return div
  },

  // ---- STEP 2: Time slots ----
  timeStep() {
    const div = c('div', 'space-y-5 py-2')
    div.appendChild(c('h2', 'text-2xl font-bold tracking-tight', 'Выберите время'))
    if (S.date) div.appendChild(c('p', 'text-sm text-white/40', fmtDate(S.date)))

    const grid = c('div', 'grid grid-cols-2 gap-3 mt-2')
    const busy = S.date ? (S.booked[S.date] || []) : []

    TIME_SLOTS.forEach(t => {
      const taken = busy.includes(t)
      const btn = c('button', `time-slot py-4 px-4 rounded-2xl text-sm font-medium border text-center ${
        S.time === t ? 'selected bg-white text-[#0a0a0a] border-white' :
        taken ? 'disabled bg-white/[0.02] border-white/[0.05] text-white/20' :
        'bg-white/[0.02] border-white/[0.08] text-white/70 hover:bg-white/[0.06]'
      }`, t)
      btn.disabled = taken
      if (!taken) btn.onclick = () => { S.time = t; this.render(2); this.ui() }
      grid.appendChild(btn)
    })
    div.appendChild(grid)
    return div
  },

  // ---- STEP 3: Confirmation + form ----
  confStep() {
    const svc = getSvc(S.serviceId)
    if (!svc) return this.svcStep()

    const div = c('div', 'space-y-5 py-2')
    div.appendChild(c('h2', 'text-2xl font-bold tracking-tight', 'Подтверждение'))

    const sum = c('div', 'p-4 rounded-2xl bg-white/[0.03] border border-white/[0.06] space-y-3')
    sum.innerHTML = `
      <div class="flex items-center justify-between"><span class="text-sm text-white/40">Услуга</span><span class="text-sm font-medium text-right">${svc.title}</span></div>
      <div class="flex items-center justify-between"><span class="text-sm text-white/40">Дата</span><span class="text-sm font-medium">${S.date ? fmtDate(S.date) : '—'}</span></div>
      <div class="flex items-center justify-between"><span class="text-sm text-white/40">Время</span><span class="text-sm font-medium">${S.time || '—'}</span></div>
      <div class="flex items-center justify-between pt-2 border-t border-white/[0.06]"><span class="text-sm text-white/40">Стоимость</span><span class="text-base font-bold">${fmtPrice(svc.price)}</span></div>
    `
    div.appendChild(sum)

    const f = c('div', 'space-y-3')
    const nm = mkInput('text', 'Ваше имя *', S.name, 'fn')
    const ph = mkInput('tel', 'Телефон *', S.phone, 'fp')
    const cm = mkTA('Комментарий (дизайн, пожелания...)', S.comment, 'fc')
    const nh = mkHint('nh', 'Пожалуйста, введите имя')
    const phh = mkHint('ph', 'Пожалуйста, введите номер телефона')

    f.appendChild(nm); f.appendChild(nh); f.appendChild(ph); f.appendChild(phh); f.appendChild(cm)
    div.appendChild(f)

    nm.oninput = () => { S.name = nm.value; nm.classList.remove('error'); nh.classList.add('hidden') }
    ph.oninput = () => {
      S.phone = ph.value.replace(/[^0-9+]/g, '')
      ph.value = S.phone
      ph.classList.remove('error'); phh.classList.add('hidden')
    }
    cm.oninput = () => { S.comment = cm.value }

    return div
  },

  // ---- STEP 4: Success ----
  okStep() {
    const svc = getSvc(S.serviceId)
    const div = c('div', 'flex flex-col items-center justify-center text-center py-8 space-y-6')
    div.innerHTML = `
      <div class="success-checkmark">
        <svg viewBox="0 0 72 72"><circle class="circle" cx="36" cy="36" r="30"/><path class="check" d="M22 36l10 10 18-18"/></svg>
      </div>
      <div><h2 class="text-2xl font-bold tracking-tight mb-1">Вы записаны!</h2><p class="text-sm text-white/40">Я жду вас в студии</p></div>
      <div class="p-4 rounded-2xl bg-white/[0.03] border border-white/[0.06] text-left w-full space-y-2 text-sm">
        <div class="flex justify-between"><span class="text-white/40">Услуга</span><span class="font-medium">${svc ? svc.title : ''}</span></div>
        <div class="flex justify-between"><span class="text-white/40">Дата</span><span class="font-medium">${S.date ? fmtDate(S.date) : ''}</span></div>
        <div class="flex justify-between"><span class="text-white/40">Время</span><span class="font-medium">${S.time}</span></div>
        <div class="flex justify-between pt-2 border-t border-white/[0.06]"><span class="text-white/40">Цена</span><span class="font-bold">${svc ? fmtPrice(svc.price) : ''}</span></div>
      </div>
      <div class="flex flex-wrap gap-3 justify-center pt-2">
        <a href="https://t.me" target="_blank" class="flex items-center gap-2 px-5 py-3 rounded-2xl bg-white/[0.04] border border-white/[0.08] text-sm text-white/70 hover:bg-white/[0.08] transition-all">
          <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 24 24"><path d="M11.944 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0a12 12 0 0 0-.056 0zm4.962 7.224c.1-.002.321.023.465.14a.506.506 0 0 1 .171.325c.016.093.036.306.02.472-.18 1.898-.962 6.502-1.36 8.627-.168.9-.499 1.201-.82 1.23-.696.065-1.225-.46-1.9-.902-1.056-.693-1.653-1.124-2.678-1.8-1.185-.78-.417-1.21.258-1.91.177-.184 3.247-2.977 3.307-3.23.007-.032.014-.15-.056-.212s-.174-.041-.249-.024c-.106.024-1.793 1.14-5.061 3.345-.48.33-.913.49-1.302.48-.428-.008-1.252-.241-1.865-.44-.752-.245-1.349-.374-1.297-.789.027-.216.325-.437.893-.663 3.498-1.524 5.83-2.529 6.998-3.014 3.332-1.386 4.025-1.627 4.476-1.635z"/></svg>
          Telegram
        </a>
        <a href="https://wa.me" target="_blank" class="flex items-center gap-2 px-5 py-3 rounded-2xl bg-white/[0.04] border border-white/[0.08] text-sm text-white/70 hover:bg-white/[0.08] transition-all">
          <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 24 24"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/></svg>
          WhatsApp
        </a>
      </div>
      <p class="text-xs text-white/30 pt-4">Закроется через 5 секунд</p>
    `
    setTimeout(() => this.close(), 5000)
    return div
  },

  // ---- Submit ----
  async submit() {
    if (S.loading) return
    S.loading = true; this.ui()
    const svc = getSvc(S.serviceId)
    const { data, error } = await createBooking({
      name: S.name.trim(), phone: S.phone.trim(), service: svc ? svc.title : '', date: S.date, time: S.time, comment: S.comment.trim()
    })
    S.loading = false
    if (error) { showToast(error.message || 'Ошибка. Попробуйте снова.', 4000); this.ui(); return }
    sendEmail({ name: S.name.trim(), service: svc ? svc.title : '', date: S.date ? fmtDate(S.date) : '', time: S.time })
    this.go(4)
  },

  // ---- UI update ----
  ui() {
    const svc = getSvc(S.serviceId)

    // Dots
    $qa('.step-dot').forEach((dot, i) => {
      dot.className = `step-dot w-2 h-2 rounded-full transition-all duration-300 ${i <= S.step ? 'bg-white/60' : 'bg-white/20'}`
    })

    // Back
    const bb = $id('bookingBack')
    if (bb) bb.style.visibility = S.step === 4 ? 'hidden' : 'visible'

    // CTA
    const cta = $id('bookingCTA')
    if (!cta) return
    cta.disabled = S.loading

    if (S.loading) { cta.innerHTML = '<span class="spinner"></span>'; return }

    const steps = [
      () => { cta.textContent = svc ? `Продолжить — ${fmtPrice(svc.price)}` : 'Выберите услугу'; cta.disabled = !svc },
      () => { cta.textContent = S.date ? 'Выбрать время' : 'Выберите дату'; cta.disabled = !S.date },
      () => { cta.textContent = S.time ? 'Подтвердить запись' : 'Выберите время'; cta.disabled = !S.time },
      () => { cta.textContent = `Подтвердить — ${svc ? fmtPrice(svc.price) : ''}`; cta.disabled = false },
      () => { cta.textContent = 'Вернуться на главную'; cta.disabled = false },
    ]
    if (steps[S.step]) steps[S.step]()
  },

  validate() {
    let ok = true
    const fn = $id('fn'), fp = $id('fp'), nh = $id('nh'), ph = $id('ph')
    if (!S.name.trim()) { fn?.classList.add('error'); nh?.classList.remove('hidden'); ok = false }
    if (!S.phone.trim()) { fp?.classList.add('error'); ph?.classList.remove('hidden'); ok = false }
    return ok
  },
}

// ==================== SUPABASE ====================

let supabaseClient = null
;(function initSupabase() {
  if (SUPABASE_URL && SUPABASE_ANON_KEY && !SUPABASE_URL.includes('YOUR_')) {
    if (typeof supabaseJs !== 'undefined') {
      supabaseClient = supabaseJs.createClient(SUPABASE_URL, SUPABASE_ANON_KEY)
    }
  }
})()

async function fetchBooked() {
  if (!supabaseClient) return {}
  const start = fmtISO(new Date(S.year, S.month, 1))
  const end = fmtISO(new Date(S.year, S.month + 1, 0))
  const { data, error } = await supabaseClient.from('bookings').select('date, time').gte('date', start).lte('date', end)
  if (error) { console.warn(error.message); return {} }
  const map = {}
  data.forEach(r => { if (!map[r.date]) map[r.date] = []; map[r.date].push(r.time) })
  return map
}

async function createBooking(d) {
  if (!supabaseClient) { await new Promise(r => setTimeout(r, 1000)); return { data: { id: Date.now() }, error: null } }
  const { data, error } = await supabaseClient.from('bookings').insert([d]).select()
  if (error && error.code === '23505') return { data: null, error: new Error('Это время уже занято.') }
  return { data, error }
}

// ==================== EMAIL ====================

function sendEmail(d) {
  if (!EMAILJS_PUBLIC_KEY || EMAILJS_PUBLIC_KEY.includes('YOUR_') || typeof emailjs === 'undefined') return
  try {
    emailjs.send(EMAILJS_SERVICE_ID, EMAILJS_TEMPLATE_ID, {
      to_name: d.name, service: d.service, date: d.date, time: d.time,
      message: `Подтверждение записи на ${d.date} в ${d.time}`,
    })
  } catch (e) { console.warn(e) }
}

// ==================== TOAST ====================

function showToast(msg, dur) {
  const t = $id('toast')
  if (!t) return
  t.textContent = msg; t.classList.add('show')
  clearTimeout(t._t); t._t = setTimeout(() => t.classList.remove('show'), dur || 3000)
}

// ==================== DOM HELPERS ====================

function c(tag, cls, txt) {
  const el = document.createElement(tag)
  if (cls) el.className = cls
  if (txt) el.textContent = txt
  return el
}

function mkInput(type, ph, val, id) {
  const el = document.createElement('input')
  el.type = type; el.className = 'input-field'; el.placeholder = ph
  el.value = val; el.id = id; el.autocomplete = type === 'tel' ? 'tel' : 'name'
  return el
}

function mkTA(ph, val, id) {
  const el = document.createElement('textarea')
  el.className = 'input-field resize-none'; el.placeholder = ph
  el.rows = 3; el.value = val; el.id = id
  return el
}

function mkHint(id, txt) {
  const el = document.createElement('p')
  el.className = 'text-[11px] text-red-400/80 hidden'; el.id = id; el.textContent = txt
  return el
}

// ==================== INIT ====================

function init() {
  // --- Booking buttons: event delegation ---
  document.addEventListener('click', function(e) {
    var target = e.target
    // Walk up to find matching element
    while (target && target !== document.body) {
      if (target.matches && target.matches('.openBookingBtn, #openBooking, .service-card-landing')) {
        var sid = target.getAttribute ? target.getAttribute('data-service-id') : null
        B.open(sid ? parseInt(sid) : null)
        return
      }
      target = target.parentElement
    }
  })

  // --- Direct bindings ---
  var closeBtn = $id('bookingClose')
  var backBtn = $id('bookingBack')
  var overlay = $id('bookingOverlay')
  var ctaBtn = $id('bookingCTA')

  if (closeBtn) closeBtn.onclick = function() { B.close() }
  if (backBtn) backBtn.onclick = function() { B.back() }
  if (overlay) overlay.onclick = function(e) { if (e.target === overlay) B.close() }

  document.addEventListener('keydown', function(e) { if (e.key === 'Escape') B.close() })

  if (ctaBtn) ctaBtn.onclick = function() {
    switch (S.step) {
      case 0: if (S.serviceId) B.go(1); break
      case 1: if (S.date) B.go(2); break
      case 2: if (S.time) B.go(3); break
      case 3: if (B.validate()) B.submit(); break
      case 4: B.close(); break
    }
  }

  // --- Reveal animations ---
  var els = document.querySelectorAll('section > div > *')
  var obs = new IntersectionObserver(function(entries) {
    entries.forEach(function(entry) {
      if (entry.isIntersecting) { entry.target.classList.add('visible'); obs.unobserve(entry.target) }
    })
  }, { threshold: 0.1, rootMargin: '0px 0px -40px 0px' })
  els.forEach(function(el) { el.classList.add('reveal'); obs.observe(el) })
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', init)
} else {
  init()
}
